### PR TITLE
Update ssl option doc README

### PR DESCRIPTION
**Pull request by y-ken**
There are ssl option implementation but README does not have the information.
https://github.com/embulk/embulk-input-jdbc/blob/master/embulk-input-mysql/src/main/java/org/embulk/input/MySQLInputPlugin.java#L50-L52

### CODE REVIEW

**Comment by y-ken** [comment]
@sakama or @hito4t  could you please check this?

**Comment by hito4t** [comment]
@y-ken 
Thank you for the PR!

The `ssl` option of embulk-input-mysql is same as the `ssl` option of embulk-output-mysql.
How about copying readme from embulk-output-mysql?
https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-mysql/README.md
<pre>
- **ssl**: use SSL to connect to the database (string, default: `disable`. `enable` uses SSL without server-side validation and `verify` checks the certificate. For compatibility reasons, `true` behaves as `enable` and `false` behaves as `disable`.
</pre>

**Comment by y-ken** [comment]
@hito4t 
Got it. After that, all of readme has these ssl option description.

```
$ grep ssl embulk-input-*/README.md
embulk-input-jdbc/README.md:- **ssl**: use SSL to connect to the database (string, default: `disable`. `enable` uses SSL without server-side validation and `verify` checks the certificate. For compatibility reasons, `true` behaves as `enable` and `false` behaves as `disable`.)
embulk-input-mysql/README.md:- **ssl**: use SSL to connect to the database (string, default: `disable`. `enable` uses SSL without server-side validation and `verify` checks the certificate. For compatibility reasons, `true` behaves as `enable` and `false` behaves as `disable`.
embulk-input-postgresql/README.md:- **ssl**: enables SSL. Data will be encrypted but CA or certification will not be verified (boolean, default: false)
embulk-input-redshift/README.md:- **ssl**: enables SSL. Data will be encrypted but CA or certification will not be verified (boolean, default: false)
```

**Comment by y-ken** [comment]
@hito4t 
Got it. After that, all of readme has these ssl option description.

```
$ grep ssl embulk-input-*/README.md
embulk-input-jdbc/README.md:- **ssl**: use SSL to connect to the database (string, default: `disable`. `enable` uses SSL without server-side validation and `verify` checks the certificate. For compatibility reasons, `true` behaves as `enable` and `false` behaves as `disable`.)
embulk-input-mysql/README.md:- **ssl**: use SSL to connect to the database (string, default: `disable`. `enable` uses SSL without server-side validation and `verify` checks the certificate. For compatibility reasons, `true` behaves as `enable` and `false` behaves as `disable`.)
embulk-input-postgresql/README.md:- **ssl**: enables SSL. Data will be encrypted but CA or certification will not be verified (boolean, default: false)
embulk-input-redshift/README.md:- **ssl**: enables SSL. Data will be encrypted but CA or certification will not be verified (boolean, default: false)
```

**Comment by hito4t** [comment]
@y-ken 
Thank you!

The type of the `ssl` option in embulk-input-postgresql and embulk-input-redshift is `boolean`, although the type of the `ssl` option in embulk-input-mysql is `enum Ssl`.
And because embulk-input-jdbc doesn't have `ssl` option, we should remove it from the readme.

**Comment by y-ken** [comment]
oh, does it need to remove ssl option line from README for embulk-input-jdbc?

```
embulk-input-jdbc/README.md:- **ssl**: use SSL to connect to the database (string, default: `disable`. `enable` uses SSL without server-side validation and `verify` checks the certificate. For compatibility reasons, `true` behaves as `enable` and `false` behaves as `disable`.)
```

**Comment by hito4t** [comment]
@y-ken 
Yes, neither `JdbcInputPlugin.GenericPluginTask` interface nor its super interface (`AbstractJdbcInputPlugin.InputPlugin`) have the `ssl` property.
Would you update README for embulk-input-jdbc?

**Comment by y-ken** [comment]
@hito4t it seems some results, but it does not effect to use ssl. does it correct?
$ grep -r -i "ssl" ./embulk-input-jdbc/
./embulk-input-jdbc//src/main/java/org/embulk/input/jdbc/Ssl.java:public enum Ssl
./embulk-input-jdbc//src/main/java/org/embulk/input/jdbc/Ssl.java:    public static Ssl fromString(String value)
./embulk-input-jdbc//src/main/java/org/embulk/input/jdbc/Ssl.java:            throw new ConfigException(String.format("Unknown SSL value '%s'. Supported values are enable, true, disable, false or verify.", value));

**Comment by hito4t** [comment]
@y-ken 
Thank you!

> it seems some results, but it does not effect to use ssl. does it correct?

`embulk-input-jdbc/src/main/java/org/embulk/input/jdbc/Ssl.java` is a class shared among embulk-input-jdbc plugins.
But embulk-input-jdbc itself doesn't use `Ssl` class.

**Pull request merged**
