### PR TITLE
Adding support for incremental loading using timestamp and timestamptz types to PostgreSQL

### PR DESCRIPTION
**Pull request by frsyuki**
This PR assumes #78. Diff from #78 is https://github.com/embulk/embulk-input-jdbc/compare/hstore-json-ext...incremental-timestamp

### CODE REVIEW

**Comment by sakama** [comment]
I tested with some different timezone with PostgreSQL 9.5.4 .
This feature seems to work fine 👍

**Comment by sakama** [comment]
@hito4t Sorry to bother you with many WIP pull-requests.
Do you have any concerns about this feature?

If nothing, we want you to merge this one and release new version.
CI failure should be fixed by #80.

**Comment by muga** [comment]
I will merge this PR into master branch instead of #76 and #78. We might need to refactor and improve experimental Travis CI settings but it's optional for now. 

@frsyuki @hito4t If you have any concerns, please let me know.

**Comment by muga** [comment]
Merged.

**Pull request merged**
