### PR TITLE
Support JSON type for MySQL

### PR DESCRIPTION
**Pull request by tvhung83**
Currently, `json` type of MySQL will be mapped to `String` type of Embulk. This PR will map it to `json` type of Embulk. It also drop support of Java 7, and upgrade dependencies to latest Embulk version.

### CODE REVIEW

**Comment by dmikurube** [comment]
The Java 8 part looks good to me. Concerns are:

* Compatibility from previous versions of the MySQL plugin.
* Making it Java 8 means it will run only on Embulk v0.9+.

**Comment by hito4t** [comment]
@dmikurube 
Thank you for review!


> Compatibility from previous versions of the MySQL plugin.

I'm concerned with that too, but I think JSON should be converted JSON as embulk-input-postgresql does.
The older embulk-input-mysql was not able to support JSON type because the bundled Connector/J (5.1.34) doesn't support MySQL 5.7, which begins to support JSON type.
But now we can support JSON type in default.
(Actually, we was able to support JSON type in embulk-input-mysql 0.8.5, which can use any JDBC driver.)

We should announce and warn about the incompatibility.

@tvhung83 
- It will work, but would you handle JSON type in `sqlTypeToValueType` method, not in `newColumnGetter` method, as `org.embulk.input.postgresql.getter.PostgreSQLColumnGetterFactory` does?

- Can you add `testJson` to `org.embulk.input.mysql.BasicTest` ?

**Comment by tvhung83** [comment]
@hito4t 
Thank you for your comments, will add and confirm here again.

**Comment by tvhung83** [comment]
@hito4t 
Sorry for late update. Please take a look again when you got a chance, thanks.

**Comment by hito4t** [comment]
@tvhung83 
Thank you!
It seems very good!

@dmikurube 
Can you review ".travis.yml"?

**Comment by hito4t** [comment]
@dmikurube 
@sakama 
Thank you!

**Pull request merged**
