### PR TITLE
Clarify supported types for incremental loading

### PR DESCRIPTION
**Pull request by hito4t**
- Clarified supported types for incremental loading in README.
- Elaborated error messages when pattern of timestamp value in `last_record` is invalid.
- Added tests for incremental loading.

### CODE REVIEW

**Comment by hito4t** [comment]
Travis error
<pre>
$ ~/bin/install-jdk.sh --target "/home/travis/openjdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "GPL" --cacerts
Ignoring license option: GPL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
</pre>

**Comment by hito4t** [comment]
@sakama 
It seems that Travis couldn't install openjdk8.
Can you fix this problem?

**Comment by sakama** [comment]
hmm, let me check.

**Comment by sakama** [comment]
It seems `dist: trusty` is the only version that we can install JDK8.
But Trusty is EOL and we can't install MySQL package.

`dist: trusty` (Ubuntu 14.04) EOL > Work
`dist: xenial` (Ubuntu 16.04) > Doen't work
`dist: bionic` (Ubuntu 18.04) > Doesn't work

Solution might be
1. Wait until Travis fix this problem
2. Use `dist:trusty` as a temporal solution + Docker test env https://github.com/embulk/embulk-input-jdbc/pull/154
3. Use Gravis-CI as a temporal solution to build Java env. I've never used this, though.
   https://github.com/DanySK/Gravis-CI

**Comment by sakama** [comment]
Or use Circle CI?
Circle CI allows us to connect to a server via SSH for debugging.

**Comment by hito4t** [comment]
@sakama 
I noticed that the travis log is as follows.
<pre>
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
</pre>

I think `dist: xernial` in `.travis.yml` should be `dist: xenial`.
It seems that `xenial` supports openjdk8.
https://docs.travis-ci.com/user/reference/xenial/

**Comment by sakama** [comment]
@hito4t Oh, That was my embarrassed mistake.
I created another PR to fix it https://github.com/embulk/embulk-input-jdbc/pull/170

**Pull request merged**
