### PR TITLE
Remove embulk-input-db2 and embulk-input-oracle

### PR DESCRIPTION
**Pull request by dmikurube**
As we discussed in https://github.com/embulk/embulk-input-jdbc/pull/206#issuecomment-846845438, we're going to remove `embulk-input-db2` and `embulk-input-oracle` from this repository.

### CODE REVIEW

**Comment by dmikurube** [comment]
@hito4t For the forks of `db2` and `oracle`, please fork it from v0.12.2!

**Review by vietnguyen-td — APPROVED** [review]
LGTM

**Review by hito4t — APPROVED** [review]
LGTM!

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
