### PR TITLE
Add Ssl enum

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Add enum Ssl for support SSL option (ex. embulk-input-mysql).

### CODE REVIEW

**Comment by hito4t** [comment]
Is this PR needed?
The PR #109 contains Ssl enum.

**Comment by hiroyuki-sato** [comment]
I just want to separate this PR and #109. But I didn't know how to do it.

**Comment by hito4t** [comment]
I think you don't need to separate #108 and #109 .
Why do you want to do?

**Comment by hiroyuki-sato** [comment]
OK, I close this issue.
I just wanted to create PRs like the following. 
I thought this way convenient for future development.

* This PR introduce SSL enum for all plugins. 
* The #109 PR introduce `ssl` option for input-mysql.

**Pull request closed without merging**
