### PR TITLE
Use traditional constructors of TimestampFormatter and TimestampParser against deprecation: Fix #118

### LINKED ISSUE #118: The constructor of `org.embulk.spi.time.TimestampFormatter` has been deprecated in Embulk 0.8.29.
The constructor of org.embulk.spi.time.TimestampFormatter has been deprecated in Embulk 0.8.29.

https://gist.github.com/k0uki/63a6fbdee7b5c67f83fea36a0714b09b

### PR DESCRIPTION
**Pull request by dmikurube**
Trying to workaround the deprecation on the Embulk core side.

@hito4t @muga Can you have a look?

### CODE REVIEW

**Comment by dmikurube** [comment]
Ah, we have to deal with the CircleCI failure... Okay.

**Comment by dmikurube** [comment]
#122 would fix the build failure.

**Comment by dmikurube** [comment]
Rebased onto #122 merged in `master`.

@hito4t Can you have another look, and release a new version if it looks fine to you?

**Comment by hito4t** [comment]
I've looked!

**Comment by dmikurube** [comment]
Thanks!!

**Comment by hito4t** [comment]
I've released a new version!

**Pull request merged**
