### PR TITLE
Feature default column options

### PR DESCRIPTION
**Pull request by yoyama**
This 'default_column_options' supports column_options for each embulk type as default.

### CODE REVIEW

**Comment by hito4t** [comment]
Thank you for the PR!
It must be very useful feature.

I have some comments as follows.
- I think if the key of `default_column_options` is value_type (sql type) instead of embulk type, this feature is more useful. For example, we can easily write yml for converting all decimal columns to string. And we can set different timestamp format for date column and datetime column. What do you think?
- In `AbstractJdbcInputPlugin#newColumnGetters`, `c_type` doesn't meet the Java naming standards. It should be `cType` or `columnType`.
- In `AbstractJdbcInputPlugin#columnOptionOf`, `a.or(b).or(c)` is slightly readable than `a.or(b.or(c))`.
- `ColumnGetterFactory#defaultColumnOptions` is not used.

**Comment by yoyama** [comment]
Changed the key from value type to JDBC type as result of discussion.

**Comment by hito4t** [comment]
Thanks!

But these don't seem to be fixed yet. Please verify.
- In `AbstractJdbcInputPlugin#columnOptionOf`, a.or(b).or(c) is slightly readable than a.or(b.or(c)).
- `ColumnGetterFactory#defaultColumnOptions` is not used.

**Comment by yoyama** [comment]
Thank you for your reviews.
I fixed them. 
Could you review again?

**Comment by hito4t** [comment]
Thank you!

**Pull request merged**
