### PR TITLE
Replace jTDS by new mssql:jdbc

### PR DESCRIPTION
**Pull request by hieudion**
The jTDS lib is quite old, we should replace it with the new mssql:jdbc.

jTDS is too old to use recently. It has not been maintained for a long time, and it can have security issues. It may be a good time to replace it with Microsoft’s official one — that is now in MIT license.

To keep the behavior the same as the old version, for some data types like `date`, `time`, `datetime2`, `datetimeoffset` and `sql_variant`, which treated differently in the new version, will be considered as `nvarchar`, followed jTDS lib.

### CODE REVIEW

**Comment by hito4t** [comment]
@hieudion 
Thank you for the PR!
I'll merge it after fixing the Travis error and writing some tests.

@dmikurube  @sakama 
Can you fix the Travis error?
<pre>
The following packages have unmet dependencies:
 mysql-client : Depends: mysql-client-5.5 but it is not going to be installed
 mysql-server : Depends: mysql-server-5.5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
apt-get.diagnostics
apt-get install failed
...
Reading package lists...
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
W: The repository 'https://packagecloud.io/github/git-lfs/ubuntu trusty InRelease' is not signed.
W: There is no public key available for the following key IDs:
6B05F25D762E3157  
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install mysql-server mysql-client" failed and exited with 100 during .
</pre>

**Comment by sakama** [comment]
I'm trying to fix CI failure on https://github.com/embulk/embulk-input-jdbc/pull/165

**Comment by sakama** [comment]
Finished fixing CI failure https://github.com/embulk/embulk-input-jdbc/pull/165

**Comment by hito4t** [comment]
I've merged after restoring jTDS driver for compatibility.

**Pull request closed without merging**
