### PR TITLE
Add mysql ssl option

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
The embulk-input-mysql support SSL connection. 
This PR require PR #108.

@hito4t Please take a look when you can.

### CODE REVIEW

**Comment by hito4t** [comment]
Thank you!
Would you update README?

**Comment by hiroyuki-sato** [comment]
OK. Thanks. I'll update it later.

**Comment by hiroyuki-sato** [comment]
@hito4t I updated README. Please take a look when you can.

**Comment by hito4t** [comment]
Thank you!
I'm sorry, I had forgotten the following question.
What is the reason for upgrading MySQL connector?

**Comment by hiroyuki-sato** [comment]
I'll double check later. 
As far as I remember It's #106 related issue.

I cannot connect mysql server without `serverTimezone` using Connector/J 5.1.34.
Do I need to create new PR for update Connect/J?

|---------|-----|--------------------------------------|
| 5.1.34    | NG  | `{ useLegacyDatetimeCode: false }`   |
| 5.1.34    | OK | `{ useLegacyDatetimeCode: false, serverTimezone: UTC }`   |
| 5.1.42    | OK  | `{ useLegacyDatetimeCode: false }`   |

[My Tweet](https://twitter.com/hiroysato/status/867330496962805760)

**Comment by hito4t** [comment]
@hiroyuki-sato 
Thank you!
The results may be caused by the following change in Connector/J 5.1.35 .
> A java.sql.date value was stored incorrectly on the server and also returned incorrectly if the client and the server were in different time zones when useLegacyDatetimeCode=false or useTimezone=true. This was due to the time-zone conversion performed by Connector/J on the SQL DATE type. To avoid the issue, a new property noTimezoneConversionForDateType has been created for Connector/J, which is set to “true” by default, preventing Connector/J to perform the kind of time-zone conversion that caused this bug. 

https://dev.mysql.com/doc/relnotes/connector-j/5.1/en/news-5-1-35.html

We should change warning message if updating Connector/J .
> You may need to set options `useLegacyDatetimeCode` and `serverTimezone`

https://github.com/embulk/embulk-input-jdbc/blob/master/embulk-input-mysql/src/main/java/org/embulk/input/MySQLTimeZoneComparison.java#L60

**Comment by hiroyuki-sato** [comment]
@hito4t Thank you for your comment. 

I'll read `noTimezoneConversionForDateType` usage. 
Let's plan for feature implementation about embulk-ouput-mysql.

What do you think the following plan?

- First update
  - Introduce comparison timezone between server and client. 
  - If both timezones are different, log message `useLegacyDatetimeCode and serverTimezone`
  - Add warning message like `next version will update Connector/J. please take care..`
  - Introduce SSL option. 
  - Don't update Connector/J
- Second update (a few week or month later after the first update)
  - Update Connector/J  5.1.42 or later
  - Change the log message `useLegacyDatetimeCode and serverTimezone`

**Comment by hito4t** [comment]
@hiroyuki-sato 
Thank you for your suggestion!
I agree.

By the way,
> Introduce comparison timezone between server and client.
> If both timezones are different, log message useLegacyDatetimeCode and serverTimezone
they were already released in 0.8.3 .

**Comment by hiroyuki-sato** [comment]
@hito4t 
I reverted Connector/J version to 5.1.4.
Please take a look again. 
I'll separate new PR for output Connector/J version warning. 

I've missed seeing 0.8.3 release.

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
