### PR TITLE
Add support for Intersystems Cache

### PR DESCRIPTION
**Pull request by kakoni**
This pull requests adds initial support for intersystems cache database.

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
@kakoni 

Thnak you for creating PR. 

I don't know much about `InterSystems Cache`.
Is it http://www.intersystems.com ?

I **personally** it's better to develop it as a separate plugin.
It is the reason that we don't have a test environment for this database.

What do you think to develop is as separate plugin like [embulk-input-vertica](https://github.com/sonots/embulk-input-vertica/)?
This plugin use embulk-input-jdbc.

@hito4t What do you think?

**Comment by hito4t** [comment]
@kakoni 
Thank you for the PR!

We (embulk-output-jdbc maintainers) have considered deliberately, and as @hiroyuki-sato wrote above, we suggest developing this plugin in your repository without merging to this repository.
Because we've never used InterSystems Cache and can't maintain this plugin.

embulk-input-jdbc jars are uploaded to bintray and you can use them as libraries.

**Comment by hiroyuki-sato** [comment]
@kakoni 

You can create embulk-input-intersystems_cache with the following steps. 

* Execute `embulk new java-input intersystems_cache`
* cd embulk-input-intersystems_cache
* Edit build.gradle.(See below)
  * Add `compile  "org.embulk.input.jdbc:embulk-input-jdbc:0.8.4"`
  * Add maven repositories
* Copy your source into `src` directory.
* Compile it witn `./gradlew classpath`
* Test `embulk run -I /path/to/embulk-input-intersystems_cache/lib cofnig.yml`

Please let me know if you have any questions about develop plugin. 

```
repositories {
    mavenCentral()
    jcenter()
    // add following blocks
    maven {
        url "http://dl.bintray.com/embulk-input-jdbc/maven"
    }

}
//...
dependencies {
    compile  "org.embulk:embulk-core:0.8.25"
    provided "org.embulk:embulk-core:0.8.25"
    compile  "org.embulk.input.jdbc:embulk-input-jdbc:0.8.4" // <-- add this line

    // compile "YOUR_JAR_DEPENDENCY_GROUP:YOUR_JAR_DEPENDENCY_MODULE:YOUR_JAR_DEPENDENCY_VERSION"
    testCompile "junit:junit:4.+"
}
```

Best regards.

**Comment by kakoni** [comment]
Yes Intersystems Cache is database used quite much in healthcare/finance. 
Anyway, made this into separate project as per your nice instructions. Thank you.
Moved to https://github.com/kakoni/embulk-input-cache

**Comment by dmikurube** [comment]
@kakoni Hi, thanks for your interests in Embulk, and making the new plugin!

Let me share some points to care about Embulk plugin naming. Embulk plugin's namespace is, unfortunately, really global and universal at rubygems.org. Once `embulk-input-something` is released on RubyGems, another person cannot release another plugin with the same name `embulk-input-something`.

IMHO, the name of the plugin `embulk-input-cache` sounds so general to me... "`cache`" reminds us a general "cache", not Intersystems' specific product "Cache". We're concerned that:

1. Users who want to use with Intersystems' Cache may not find the plugin,
2. Other users may be confused with the general name,
3. The name may conflict with something like a general "cache" in the future.

Do you mind if we ask you to rename the plugin to `embulk-input-intersystems_cache` or some other name which is explicitly specific to Intersystems Cache?

**Comment by kakoni** [comment]
dmikurube Ok, I'll rename it. Thanks for the tip.

**Comment by dmikurube** [comment]
Thanks for your cooperation! :)

**Pull request closed without merging**
