### PR TITLE
Add embulk-input-clickhouse

### PR DESCRIPTION
**Pull request by tac0x2a**
I implemented embulk-input plugin for [ClickHouse](https://clickhouse.yandex/).
This PR include just only simple features. (without resume and incremental loading).

And, [yandex/clickhouse-jdbc](https://github.com/yandex/clickhouse-jdbc) needs to fix by merge [this PR](https://github.com/yandex/clickhouse-jdbc/pull/238)
So, please test with using [this branch](https://github.com/tac0x2a/clickhouse-jdbc/tree/add/getMetaData) before marge it.

# Example
This implementation is work fine.
## Definition of Table on ClickHouse 
```sql
DROP TABLE db_bench.type_test;

CREATE TABLE db_bench.type_test (
  `uid` UInt64,
  `i8` Int8,
  `i16` Int16,
  `i32` Int32,
  `i64` Int64,
  `ui8` UInt8,
  `ui16` UInt16,
  `ui32` UInt32,
  `ui64` UInt64,
  `f32` Float32,
  `f64` Float64,
  `s` String,
  `fs32` FixedString(32),
  `d` Date,
  `dt` DateTime,  
  `e8` Enum8('hello' = 1, 'world' = 2),  
  `ai32` Array(Int32),
  `astr` Array(String),
  `aui64` Array(UInt64),
  `t_i32_s` Tuple(Int32, String), 
  `create_at` DateTime
) ENGINE = MergeTree() ORDER BY uid PARTITION BY toYYYYMM(create_at);

INSERT INTO db_bench.type_test (
	uid, i8, i16, i32, i64, ui8, ui16, ui32, ui64,
	f32, f64, s, fs32, d, dt, 
	e8, ai32, astr, aui64, t_i32_s,
	create_at
) VALUES (
	1, -128, -32768, -2147483648, -9223372036854775808, 0, 0, 0, 0, 
	1.1, 2.2, 'string', 'fixed_string32', '2018-09-30', '2018-10-01 12:34:56', 
	'hello', [1,2,3], ['string4', 'string5'], [0, 18446744073709551615], tuple(1, 'tuple_string'),
	'2018-10-02 12:34:56'
);
INSERT INTO db_bench.type_test (
	uid, i8, i16, i32, i64, ui8, ui16, ui32, ui64,
	f32, f64, s, fs32, d, dt, 
	e8, ai32, astr, aui64, t_i32_s,
	create_at
) VALUES (
	2, 127, 32767, 2147483647, 9223372036854775807, 255, 65535, 4294967295, 18446744073709551615, 
	-1.0/0, 1.0/0, 'string', 'fixed_string32', '2018-09-30', '2018-10-01 12:34:56', 
	'hello', [1,2,3], ['{"like":"json"}', 'Hello,World'], [0, 42], tuple(1, 'tuple_string'),
	'2018-10-02 12:34:56'
);

-- select * from  db_bench.type_test;
```

## config.yml
```yml
in:
  type: clickhouse
  driver_path: ./lib/clickhouse-jdbc-0.1-SNAPSHOT.jar
  database: db_bench
  host: 127.0.0.1
  # connect_timeout: 300
  socket_timeout:  1000000
  query: SELECT * from db_bench.type_test
  column_options:
    ui64: {type: string}

...
```

## Result
```sh
$ embulk preview config.yml
2018-10-02 00:23:14.014 +0900: Embulk v0.9.7
2018-10-02 00:23:14.834 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2018-10-02 00:23:17.494 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/tac/.embulk/lib/gems"
2018-10-02 00:23:18.489 +0900 [INFO] (main): Started Embulk v0.9.7
2018-10-02 00:23:18.553 +0900 [INFO] (0001:preview): Loaded plugin embulk/input/clickhouse from a load path
2018-10-02 00:23:18.607 +0900 [INFO] (0001:preview): Driver registered
2018-10-02 00:23:18.609 +0900 [INFO] (0001:preview): Connecting to jdbc:clickhouse://127.0.0.1:8123/db_bench options {socket_timeout=1000000, keepAliveTimeout=30000, buffer_size=65536, connection_timeout=30000, apache_buffer_size=65536, dataTransferTimeout=10000}
2018-10-02 00:23:18.727 +0900 [INFO] (0001:preview): Using JDBC Driver 0.1
2018-10-02 00:23:19.095 +0900 [INFO] (0001:preview): Connecting to jdbc:clickhouse://127.0.0.1:8123/db_bench options {socket_timeout=1000000, keepAliveTimeout=30000, buffer_size=65536, connection_timeout=30000, apache_buffer_size=65536, dataTransferTimeout=10000}
2018-10-02 00:23:19.107 +0900 [INFO] (0001:preview): SQL: SELECT * from db_bench.type_test
2018-10-02 00:23:19.262 +0900 [INFO] (0001:preview): > 0.15 seconds
+----------+---------+----------+----------------+----------------------------+----------+-----------+---------------+----------------------+-------------------+------------+----------+----------------------------------+-------------------------+-------------------------+-----------+-------------+---------------------------------------+--------------------------+--------------------+-------------------------+
| uid:long | i8:long | i16:long |       i32:long |                   i64:long | ui8:long | ui16:long |     ui32:long |          ui64:string |        f32:double | f64:double | s:string |                      fs32:string |             d:timestamp |            dt:timestamp | e8:string | ai32:string |                           astr:string |               aui64:json |       t_i32_s:json |     create_at:timestamp |
+----------+---------+----------+----------------+----------------------------+----------+-----------+---------------+----------------------+-------------------+------------+----------+----------------------------------+-------------------------+-------------------------+-----------+-------------+---------------------------------------+--------------------------+--------------------+-------------------------+
|        2 |     127 |   32,767 |  2,147,483,647 |  9,223,372,036,854,775,807 |      255 |    65,535 | 4,294,967,295 | 18446744073709551615 |         -Infinity |   Infinity |   string | fixed_string32������������������ | 2018-09-29 15:00:00 UTC | 2018-10-01 12:34:56 UTC |     hello |     [1,2,3] | ["{\"like\":\"json\"}","Hello,World"] |                   [0,42] | (1,'tuple_string') | 2018-10-02 12:34:56 UTC |
|        1 |    -128 |  -32,768 | -2,147,483,648 | -9,223,372,036,854,775,808 |        0 |         0 |             0 |                    0 | 1.100000023841858 |        2.2 |   string | fixed_string32������������������ | 2018-09-29 15:00:00 UTC | 2018-10-01 12:34:56 UTC |     hello |     [1,2,3] |                 ["string4","string5"] | [0,18446744073709551615] | (1,'tuple_string') | 2018-10-02 12:34:56 UTC |
+----------+---------+----------+----------------+----------------------------+----------+-----------+---------------+----------------------+-------------------+------------+----------+----------------------------------+-------------------------+-------------------------+-----------+-------------+---------------------------------------+--------------------------+--------------------+-------------------------+
```

In this case, if it execute without `column_option`, we are getting exception and suggestions.
```
java.lang.NumberFormatException: 18446744073709551615 In 'ui64 UInt64' is too large for Long type.
Please set other type (string or json) in your config file :

in:
  type: clickhouse
  ...
  column_option:
    ui64: {type: string}

        at org.embulk.input.clickhouse.getter.BigIntegerColumnGetter.longColumn(BigIntegerColumnGetter.java:53)
        at org.embulk.spi.Column.visit(Column.java:48)
        at org.embulk.input.jdbc.getter.AbstractColumnGetter.getAndSet(AbstractColumnGetter.java:36)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.fetch(AbstractJdbcInputPlugin.java:582)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.run(AbstractJdbcInputPlugin.java:480)
        at org.embulk.exec.PreviewExecutor$2$1.run(PreviewExecutor.java:130)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84)
        at org.embulk.spi.util.Filters.transaction(Filters.java:42)
        at org.embulk.exec.PreviewExecutor$2.run(PreviewExecutor.java:120)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:206)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:118)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:106)
        at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:29)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:73)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:70)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:70)
        at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:151)
        at org.embulk.EmbulkRunner.previewInternal(EmbulkRunner.java:215)
        at org.embulk.EmbulkRunner.preview(EmbulkRunner.java:107)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:433)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
        at org.embulk.cli.Main.main(Main.java:26)
```

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Hello, @tac0x2a 

Thank you for creating PR.

I think It is better to develop it as a plugin.
What do you think? @hito4t?

You can download [embulk-input-jdbc.jar](https://bintray.com/embulk-input-jdbc) from bintray.
It allows extending embulk-input-jdbc class.
What do you think to create input-clickhouse as a plugin?

**Comment by tac0x2a** [comment]
Hello, @hiroyuki-sato san

Thank you for commenting and suggestion !
You mean, it is better to develop "embulk-input-clickhouse" isolated from this repo, right?

Thanks a lot.

**Comment by sakama** [comment]
Hi, @tac0x2a 

Thanks for your great contribution.
I also agree with @hiroyuki-sato 's opinion that implement ClickHouse plugin as standalone one.
There is no person in maintainers who is familiar with ClickHouse.
Then, merging this PR will make embulk-input-jdbc/* harder to maintain.

To write standalone plugin, you can refer [embulk-input-vertica](https://github.com/sonots/embulk-input-vertica).
This plugin is also written based on embulk-input-jdbc.
https://github.com/sonots/embulk-input-vertica/blob/master/build.gradle#L12
https://github.com/sonots/embulk-input-vertica/blob/master/src/main/java/org/embulk/input/VerticaInputPlugin.java#L20

I roughly checked your PR and it might not so difficult to implement new plugin based on embulk-input-jdbc

**Comment by hiroyuki-sato** [comment]
Hello, @tac0x2a 

Yes, It meant that develop standalone embulk-input-clickhouse.
The reason is the same @sakama with the opinion.

**Comment by tac0x2a** [comment]
Hi, @sakama and @hiroyuki-sato
Thank you for suggestion!

I understood your opinion, and agree with you.
I'll try to create `embulk-input-clickhouse` as standalone repo!
Thank you.

By the way, Is it possible if I want to append `embulk-input-clickhouse` to [Embulk plugins list](http://www.embulk.org/plugins/)?
I guess that page will be created by [plugin-crawler](https://github.com/embulk/plugin-crawler). Could you tell me about how should I do for appending one.

Thanks a lot!

**Comment by hiroyuki-sato** [comment]
Hello, @tac0x2a 

The official plugin lists use [rubygems](https://rubygems.org).
So, You just publish the plugin with a gem. After that, It will list it automatically.
One attention, You need to uncomment this part.
Ex) https://github.com/hiroyuki-sato/embulk-filter-calc/blob/master/build.gradle#L91

[Embulk plugin list](https://qiita.com/hiroysato/items/da45e52fb79c39547f69) in Japanese managing manually. 😄

**Comment by tac0x2a** [comment]
Hello, @hiroyuki-sato

Thank you for detailed information.
I'll try to publish plugin as gem. After that, I'll request to modify on Qiita!

Thank you so much.

**Pull request closed without merging**
